/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PathsIndexRouteImport } from './routes/paths/index'
import { Route as LessonsIndexRouteImport } from './routes/lessons/index'
import { Route as LearnIndexRouteImport } from './routes/learn/index'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as VerifyCodeRouteImport } from './routes/verify/$code'
import { Route as PathsSlugRouteImport } from './routes/paths/$slug'
import { Route as LessonsIdRouteImport } from './routes/lessons/$id'
import { Route as LearnSlugRouteImport } from './routes/learn/$slug'
import { Route as CoursesSlugRouteImport } from './routes/courses/$slug'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AuthenticatedStudioRouteImport } from './routes/_authenticated/studio'
import { Route as AuthenticatedStatsRouteImport } from './routes/_authenticated/stats'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConsoleRouteImport } from './routes/_authenticated/console'
import { Route as AuthenticatedCertificatesRouteImport } from './routes/_authenticated/certificates'
import { Route as AuthenticatedAchievementsRouteImport } from './routes/_authenticated/achievements'
import { Route as AuthenticatedConsoleIndexRouteImport } from './routes/_authenticated/console/index'
import { Route as AuthenticatedConsoleTransactionsRouteImport } from './routes/_authenticated/console/transactions'
import { Route as AuthenticatedConsoleTrafficRouteImport } from './routes/_authenticated/console/traffic'
import { Route as AuthenticatedConsoleSupportRouteImport } from './routes/_authenticated/console/support'
import { Route as AuthenticatedConsoleStudentsRouteImport } from './routes/_authenticated/console/students'
import { Route as AuthenticatedConsoleSettingsRouteImport } from './routes/_authenticated/console/settings'
import { Route as AuthenticatedConsoleSecurityRouteImport } from './routes/_authenticated/console/security'
import { Route as AuthenticatedConsoleReposRouteImport } from './routes/_authenticated/console/repos'
import { Route as AuthenticatedConsoleRealtimeRouteImport } from './routes/_authenticated/console/realtime'
import { Route as AuthenticatedConsoleQuizzesRouteImport } from './routes/_authenticated/console/quizzes'
import { Route as AuthenticatedConsoleProfileRouteImport } from './routes/_authenticated/console/profile'
import { Route as AuthenticatedConsolePlaygroundRouteImport } from './routes/_authenticated/console/playground'
import { Route as AuthenticatedConsolePlansRouteImport } from './routes/_authenticated/console/plans'
import { Route as AuthenticatedConsoleNotificationsRouteImport } from './routes/_authenticated/console/notifications'
import { Route as AuthenticatedConsoleLogsRouteImport } from './routes/_authenticated/console/logs'
import { Route as AuthenticatedConsoleLessonsRouteImport } from './routes/_authenticated/console/lessons'
import { Route as AuthenticatedConsoleLearningRouteImport } from './routes/_authenticated/console/learning'
import { Route as AuthenticatedConsoleInstructorsRouteImport } from './routes/_authenticated/console/instructors'
import { Route as AuthenticatedConsoleForumRouteImport } from './routes/_authenticated/console/forum'
import { Route as AuthenticatedConsoleFinancialRouteImport } from './routes/_authenticated/console/financial'
import { Route as AuthenticatedConsoleCoursesRouteImport } from './routes/_authenticated/console/courses'
import { Route as AuthenticatedConsoleCouponsRouteImport } from './routes/_authenticated/console/coupons'
import { Route as AuthenticatedConsoleCertificatesRouteImport } from './routes/_authenticated/console/certificates'
import { Route as AuthenticatedConsoleBlogRouteImport } from './routes/_authenticated/console/blog'
import { Route as AuthenticatedConsoleApiRouteImport } from './routes/_authenticated/console/api'
import { Route as AuthenticatedConsoleAccountRouteImport } from './routes/_authenticated/console/account'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PathsIndexRoute = PathsIndexRouteImport.update({
  id: '/paths/',
  path: '/paths/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsIndexRoute = LessonsIndexRouteImport.update({
  id: '/lessons/',
  path: '/lessons/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCodeRoute = VerifyCodeRouteImport.update({
  id: '/verify/$code',
  path: '/verify/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PathsSlugRoute = PathsSlugRouteImport.update({
  id: '/paths/$slug',
  path: '/paths/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsIdRoute = LessonsIdRouteImport.update({
  id: '/lessons/$id',
  path: '/lessons/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/learn/$slug',
  path: '/learn/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudioRoute = AuthenticatedStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStatsRoute = AuthenticatedStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConsoleRoute = AuthenticatedConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCertificatesRoute =
  AuthenticatedCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAchievementsRoute =
  AuthenticatedAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConsoleIndexRoute =
  AuthenticatedConsoleIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleTransactionsRoute =
  AuthenticatedConsoleTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleTrafficRoute =
  AuthenticatedConsoleTrafficRouteImport.update({
    id: '/traffic',
    path: '/traffic',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleSupportRoute =
  AuthenticatedConsoleSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleStudentsRoute =
  AuthenticatedConsoleStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleSettingsRoute =
  AuthenticatedConsoleSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleSecurityRoute =
  AuthenticatedConsoleSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleReposRoute =
  AuthenticatedConsoleReposRouteImport.update({
    id: '/repos',
    path: '/repos',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleRealtimeRoute =
  AuthenticatedConsoleRealtimeRouteImport.update({
    id: '/realtime',
    path: '/realtime',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleQuizzesRoute =
  AuthenticatedConsoleQuizzesRouteImport.update({
    id: '/quizzes',
    path: '/quizzes',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleProfileRoute =
  AuthenticatedConsoleProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsolePlaygroundRoute =
  AuthenticatedConsolePlaygroundRouteImport.update({
    id: '/playground',
    path: '/playground',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsolePlansRoute =
  AuthenticatedConsolePlansRouteImport.update({
    id: '/plans',
    path: '/plans',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleNotificationsRoute =
  AuthenticatedConsoleNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleLogsRoute =
  AuthenticatedConsoleLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleLessonsRoute =
  AuthenticatedConsoleLessonsRouteImport.update({
    id: '/lessons',
    path: '/lessons',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleLearningRoute =
  AuthenticatedConsoleLearningRouteImport.update({
    id: '/learning',
    path: '/learning',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleInstructorsRoute =
  AuthenticatedConsoleInstructorsRouteImport.update({
    id: '/instructors',
    path: '/instructors',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleForumRoute =
  AuthenticatedConsoleForumRouteImport.update({
    id: '/forum',
    path: '/forum',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleFinancialRoute =
  AuthenticatedConsoleFinancialRouteImport.update({
    id: '/financial',
    path: '/financial',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleCoursesRoute =
  AuthenticatedConsoleCoursesRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleCouponsRoute =
  AuthenticatedConsoleCouponsRouteImport.update({
    id: '/coupons',
    path: '/coupons',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleCertificatesRoute =
  AuthenticatedConsoleCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleBlogRoute =
  AuthenticatedConsoleBlogRouteImport.update({
    id: '/blog',
    path: '/blog',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleApiRoute = AuthenticatedConsoleApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => AuthenticatedConsoleRoute,
} as any)
const AuthenticatedConsoleAccountRoute =
  AuthenticatedConsoleAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/download': typeof DownloadRoute
  '/leaderboard': typeof LeaderboardRoute
  '/missions': typeof MissionsRoute
  '/playground': typeof PlaygroundRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/quiz': typeof QuizRoute
  '/tools': typeof ToolsRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/console': typeof AuthenticatedConsoleRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/lessons/$id': typeof LessonsIdRoute
  '/paths/$slug': typeof PathsSlugRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/blog/': typeof BlogIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/lessons/': typeof LessonsIndexRoute
  '/paths/': typeof PathsIndexRoute
  '/console/account': typeof AuthenticatedConsoleAccountRoute
  '/console/api': typeof AuthenticatedConsoleApiRoute
  '/console/blog': typeof AuthenticatedConsoleBlogRoute
  '/console/certificates': typeof AuthenticatedConsoleCertificatesRoute
  '/console/coupons': typeof AuthenticatedConsoleCouponsRoute
  '/console/courses': typeof AuthenticatedConsoleCoursesRoute
  '/console/financial': typeof AuthenticatedConsoleFinancialRoute
  '/console/forum': typeof AuthenticatedConsoleForumRoute
  '/console/instructors': typeof AuthenticatedConsoleInstructorsRoute
  '/console/learning': typeof AuthenticatedConsoleLearningRoute
  '/console/lessons': typeof AuthenticatedConsoleLessonsRoute
  '/console/logs': typeof AuthenticatedConsoleLogsRoute
  '/console/notifications': typeof AuthenticatedConsoleNotificationsRoute
  '/console/plans': typeof AuthenticatedConsolePlansRoute
  '/console/playground': typeof AuthenticatedConsolePlaygroundRoute
  '/console/profile': typeof AuthenticatedConsoleProfileRoute
  '/console/quizzes': typeof AuthenticatedConsoleQuizzesRoute
  '/console/realtime': typeof AuthenticatedConsoleRealtimeRoute
  '/console/repos': typeof AuthenticatedConsoleReposRoute
  '/console/security': typeof AuthenticatedConsoleSecurityRoute
  '/console/settings': typeof AuthenticatedConsoleSettingsRoute
  '/console/students': typeof AuthenticatedConsoleStudentsRoute
  '/console/support': typeof AuthenticatedConsoleSupportRoute
  '/console/traffic': typeof AuthenticatedConsoleTrafficRoute
  '/console/transactions': typeof AuthenticatedConsoleTransactionsRoute
  '/console/': typeof AuthenticatedConsoleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/download': typeof DownloadRoute
  '/leaderboard': typeof LeaderboardRoute
  '/missions': typeof MissionsRoute
  '/playground': typeof PlaygroundRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/quiz': typeof QuizRoute
  '/tools': typeof ToolsRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/lessons/$id': typeof LessonsIdRoute
  '/paths/$slug': typeof PathsSlugRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/blog': typeof BlogIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/learn': typeof LearnIndexRoute
  '/lessons': typeof LessonsIndexRoute
  '/paths': typeof PathsIndexRoute
  '/console/account': typeof AuthenticatedConsoleAccountRoute
  '/console/api': typeof AuthenticatedConsoleApiRoute
  '/console/blog': typeof AuthenticatedConsoleBlogRoute
  '/console/certificates': typeof AuthenticatedConsoleCertificatesRoute
  '/console/coupons': typeof AuthenticatedConsoleCouponsRoute
  '/console/courses': typeof AuthenticatedConsoleCoursesRoute
  '/console/financial': typeof AuthenticatedConsoleFinancialRoute
  '/console/forum': typeof AuthenticatedConsoleForumRoute
  '/console/instructors': typeof AuthenticatedConsoleInstructorsRoute
  '/console/learning': typeof AuthenticatedConsoleLearningRoute
  '/console/lessons': typeof AuthenticatedConsoleLessonsRoute
  '/console/logs': typeof AuthenticatedConsoleLogsRoute
  '/console/notifications': typeof AuthenticatedConsoleNotificationsRoute
  '/console/plans': typeof AuthenticatedConsolePlansRoute
  '/console/playground': typeof AuthenticatedConsolePlaygroundRoute
  '/console/profile': typeof AuthenticatedConsoleProfileRoute
  '/console/quizzes': typeof AuthenticatedConsoleQuizzesRoute
  '/console/realtime': typeof AuthenticatedConsoleRealtimeRoute
  '/console/repos': typeof AuthenticatedConsoleReposRoute
  '/console/security': typeof AuthenticatedConsoleSecurityRoute
  '/console/settings': typeof AuthenticatedConsoleSettingsRoute
  '/console/students': typeof AuthenticatedConsoleStudentsRoute
  '/console/support': typeof AuthenticatedConsoleSupportRoute
  '/console/traffic': typeof AuthenticatedConsoleTrafficRoute
  '/console/transactions': typeof AuthenticatedConsoleTransactionsRoute
  '/console': typeof AuthenticatedConsoleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/download': typeof DownloadRoute
  '/leaderboard': typeof LeaderboardRoute
  '/missions': typeof MissionsRoute
  '/playground': typeof PlaygroundRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/quiz': typeof QuizRoute
  '/tools': typeof ToolsRoute
  '/_authenticated/achievements': typeof AuthenticatedAchievementsRoute
  '/_authenticated/certificates': typeof AuthenticatedCertificatesRoute
  '/_authenticated/console': typeof AuthenticatedConsoleRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/stats': typeof AuthenticatedStatsRoute
  '/_authenticated/studio': typeof AuthenticatedStudioRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/lessons/$id': typeof LessonsIdRoute
  '/paths/$slug': typeof PathsSlugRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/blog/': typeof BlogIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/lessons/': typeof LessonsIndexRoute
  '/paths/': typeof PathsIndexRoute
  '/_authenticated/console/account': typeof AuthenticatedConsoleAccountRoute
  '/_authenticated/console/api': typeof AuthenticatedConsoleApiRoute
  '/_authenticated/console/blog': typeof AuthenticatedConsoleBlogRoute
  '/_authenticated/console/certificates': typeof AuthenticatedConsoleCertificatesRoute
  '/_authenticated/console/coupons': typeof AuthenticatedConsoleCouponsRoute
  '/_authenticated/console/courses': typeof AuthenticatedConsoleCoursesRoute
  '/_authenticated/console/financial': typeof AuthenticatedConsoleFinancialRoute
  '/_authenticated/console/forum': typeof AuthenticatedConsoleForumRoute
  '/_authenticated/console/instructors': typeof AuthenticatedConsoleInstructorsRoute
  '/_authenticated/console/learning': typeof AuthenticatedConsoleLearningRoute
  '/_authenticated/console/lessons': typeof AuthenticatedConsoleLessonsRoute
  '/_authenticated/console/logs': typeof AuthenticatedConsoleLogsRoute
  '/_authenticated/console/notifications': typeof AuthenticatedConsoleNotificationsRoute
  '/_authenticated/console/plans': typeof AuthenticatedConsolePlansRoute
  '/_authenticated/console/playground': typeof AuthenticatedConsolePlaygroundRoute
  '/_authenticated/console/profile': typeof AuthenticatedConsoleProfileRoute
  '/_authenticated/console/quizzes': typeof AuthenticatedConsoleQuizzesRoute
  '/_authenticated/console/realtime': typeof AuthenticatedConsoleRealtimeRoute
  '/_authenticated/console/repos': typeof AuthenticatedConsoleReposRoute
  '/_authenticated/console/security': typeof AuthenticatedConsoleSecurityRoute
  '/_authenticated/console/settings': typeof AuthenticatedConsoleSettingsRoute
  '/_authenticated/console/students': typeof AuthenticatedConsoleStudentsRoute
  '/_authenticated/console/support': typeof AuthenticatedConsoleSupportRoute
  '/_authenticated/console/traffic': typeof AuthenticatedConsoleTrafficRoute
  '/_authenticated/console/transactions': typeof AuthenticatedConsoleTransactionsRoute
  '/_authenticated/console/': typeof AuthenticatedConsoleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/chat'
    | '/download'
    | '/leaderboard'
    | '/missions'
    | '/playground'
    | '/profile'
    | '/projects'
    | '/quiz'
    | '/tools'
    | '/achievements'
    | '/certificates'
    | '/console'
    | '/dashboard'
    | '/stats'
    | '/studio'
    | '/blog/$slug'
    | '/courses/$slug'
    | '/learn/$slug'
    | '/lessons/$id'
    | '/paths/$slug'
    | '/verify/$code'
    | '/blog/'
    | '/courses/'
    | '/learn/'
    | '/lessons/'
    | '/paths/'
    | '/console/account'
    | '/console/api'
    | '/console/blog'
    | '/console/certificates'
    | '/console/coupons'
    | '/console/courses'
    | '/console/financial'
    | '/console/forum'
    | '/console/instructors'
    | '/console/learning'
    | '/console/lessons'
    | '/console/logs'
    | '/console/notifications'
    | '/console/plans'
    | '/console/playground'
    | '/console/profile'
    | '/console/quizzes'
    | '/console/realtime'
    | '/console/repos'
    | '/console/security'
    | '/console/settings'
    | '/console/students'
    | '/console/support'
    | '/console/traffic'
    | '/console/transactions'
    | '/console/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/chat'
    | '/download'
    | '/leaderboard'
    | '/missions'
    | '/playground'
    | '/profile'
    | '/projects'
    | '/quiz'
    | '/tools'
    | '/achievements'
    | '/certificates'
    | '/dashboard'
    | '/stats'
    | '/studio'
    | '/blog/$slug'
    | '/courses/$slug'
    | '/learn/$slug'
    | '/lessons/$id'
    | '/paths/$slug'
    | '/verify/$code'
    | '/blog'
    | '/courses'
    | '/learn'
    | '/lessons'
    | '/paths'
    | '/console/account'
    | '/console/api'
    | '/console/blog'
    | '/console/certificates'
    | '/console/coupons'
    | '/console/courses'
    | '/console/financial'
    | '/console/forum'
    | '/console/instructors'
    | '/console/learning'
    | '/console/lessons'
    | '/console/logs'
    | '/console/notifications'
    | '/console/plans'
    | '/console/playground'
    | '/console/profile'
    | '/console/quizzes'
    | '/console/realtime'
    | '/console/repos'
    | '/console/security'
    | '/console/settings'
    | '/console/students'
    | '/console/support'
    | '/console/traffic'
    | '/console/transactions'
    | '/console'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/chat'
    | '/download'
    | '/leaderboard'
    | '/missions'
    | '/playground'
    | '/profile'
    | '/projects'
    | '/quiz'
    | '/tools'
    | '/_authenticated/achievements'
    | '/_authenticated/certificates'
    | '/_authenticated/console'
    | '/_authenticated/dashboard'
    | '/_authenticated/stats'
    | '/_authenticated/studio'
    | '/blog/$slug'
    | '/courses/$slug'
    | '/learn/$slug'
    | '/lessons/$id'
    | '/paths/$slug'
    | '/verify/$code'
    | '/blog/'
    | '/courses/'
    | '/learn/'
    | '/lessons/'
    | '/paths/'
    | '/_authenticated/console/account'
    | '/_authenticated/console/api'
    | '/_authenticated/console/blog'
    | '/_authenticated/console/certificates'
    | '/_authenticated/console/coupons'
    | '/_authenticated/console/courses'
    | '/_authenticated/console/financial'
    | '/_authenticated/console/forum'
    | '/_authenticated/console/instructors'
    | '/_authenticated/console/learning'
    | '/_authenticated/console/lessons'
    | '/_authenticated/console/logs'
    | '/_authenticated/console/notifications'
    | '/_authenticated/console/plans'
    | '/_authenticated/console/playground'
    | '/_authenticated/console/profile'
    | '/_authenticated/console/quizzes'
    | '/_authenticated/console/realtime'
    | '/_authenticated/console/repos'
    | '/_authenticated/console/security'
    | '/_authenticated/console/settings'
    | '/_authenticated/console/students'
    | '/_authenticated/console/support'
    | '/_authenticated/console/traffic'
    | '/_authenticated/console/transactions'
    | '/_authenticated/console/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  DownloadRoute: typeof DownloadRoute
  LeaderboardRoute: typeof LeaderboardRoute
  MissionsRoute: typeof MissionsRoute
  PlaygroundRoute: typeof PlaygroundRoute
  ProfileRoute: typeof ProfileRoute
  ProjectsRoute: typeof ProjectsRoute
  QuizRoute: typeof QuizRoute
  ToolsRoute: typeof ToolsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  LearnSlugRoute: typeof LearnSlugRoute
  LessonsIdRoute: typeof LessonsIdRoute
  PathsSlugRoute: typeof PathsSlugRoute
  VerifyCodeRoute: typeof VerifyCodeRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  LearnIndexRoute: typeof LearnIndexRoute
  LessonsIndexRoute: typeof LessonsIndexRoute
  PathsIndexRoute: typeof PathsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paths/': {
      id: '/paths/'
      path: '/paths'
      fullPath: '/paths/'
      preLoaderRoute: typeof PathsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/': {
      id: '/lessons/'
      path: '/lessons'
      fullPath: '/lessons/'
      preLoaderRoute: typeof LessonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$code': {
      id: '/verify/$code'
      path: '/verify/$code'
      fullPath: '/verify/$code'
      preLoaderRoute: typeof VerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paths/$slug': {
      id: '/paths/$slug'
      path: '/paths/$slug'
      fullPath: '/paths/$slug'
      preLoaderRoute: typeof PathsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/$id': {
      id: '/lessons/$id'
      path: '/lessons/$id'
      fullPath: '/lessons/$id'
      preLoaderRoute: typeof LessonsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/learn/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/studio': {
      id: '/_authenticated/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AuthenticatedStudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stats': {
      id: '/_authenticated/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AuthenticatedStatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/console': {
      id: '/_authenticated/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof AuthenticatedConsoleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/certificates': {
      id: '/_authenticated/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof AuthenticatedCertificatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/achievements': {
      id: '/_authenticated/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AuthenticatedAchievementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/console/': {
      id: '/_authenticated/console/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof AuthenticatedConsoleIndexRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/transactions': {
      id: '/_authenticated/console/transactions'
      path: '/transactions'
      fullPath: '/console/transactions'
      preLoaderRoute: typeof AuthenticatedConsoleTransactionsRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/traffic': {
      id: '/_authenticated/console/traffic'
      path: '/traffic'
      fullPath: '/console/traffic'
      preLoaderRoute: typeof AuthenticatedConsoleTrafficRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/support': {
      id: '/_authenticated/console/support'
      path: '/support'
      fullPath: '/console/support'
      preLoaderRoute: typeof AuthenticatedConsoleSupportRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/students': {
      id: '/_authenticated/console/students'
      path: '/students'
      fullPath: '/console/students'
      preLoaderRoute: typeof AuthenticatedConsoleStudentsRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/settings': {
      id: '/_authenticated/console/settings'
      path: '/settings'
      fullPath: '/console/settings'
      preLoaderRoute: typeof AuthenticatedConsoleSettingsRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/security': {
      id: '/_authenticated/console/security'
      path: '/security'
      fullPath: '/console/security'
      preLoaderRoute: typeof AuthenticatedConsoleSecurityRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/repos': {
      id: '/_authenticated/console/repos'
      path: '/repos'
      fullPath: '/console/repos'
      preLoaderRoute: typeof AuthenticatedConsoleReposRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/realtime': {
      id: '/_authenticated/console/realtime'
      path: '/realtime'
      fullPath: '/console/realtime'
      preLoaderRoute: typeof AuthenticatedConsoleRealtimeRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/quizzes': {
      id: '/_authenticated/console/quizzes'
      path: '/quizzes'
      fullPath: '/console/quizzes'
      preLoaderRoute: typeof AuthenticatedConsoleQuizzesRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/profile': {
      id: '/_authenticated/console/profile'
      path: '/profile'
      fullPath: '/console/profile'
      preLoaderRoute: typeof AuthenticatedConsoleProfileRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/playground': {
      id: '/_authenticated/console/playground'
      path: '/playground'
      fullPath: '/console/playground'
      preLoaderRoute: typeof AuthenticatedConsolePlaygroundRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/plans': {
      id: '/_authenticated/console/plans'
      path: '/plans'
      fullPath: '/console/plans'
      preLoaderRoute: typeof AuthenticatedConsolePlansRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/notifications': {
      id: '/_authenticated/console/notifications'
      path: '/notifications'
      fullPath: '/console/notifications'
      preLoaderRoute: typeof AuthenticatedConsoleNotificationsRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/logs': {
      id: '/_authenticated/console/logs'
      path: '/logs'
      fullPath: '/console/logs'
      preLoaderRoute: typeof AuthenticatedConsoleLogsRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/lessons': {
      id: '/_authenticated/console/lessons'
      path: '/lessons'
      fullPath: '/console/lessons'
      preLoaderRoute: typeof AuthenticatedConsoleLessonsRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/learning': {
      id: '/_authenticated/console/learning'
      path: '/learning'
      fullPath: '/console/learning'
      preLoaderRoute: typeof AuthenticatedConsoleLearningRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/instructors': {
      id: '/_authenticated/console/instructors'
      path: '/instructors'
      fullPath: '/console/instructors'
      preLoaderRoute: typeof AuthenticatedConsoleInstructorsRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/forum': {
      id: '/_authenticated/console/forum'
      path: '/forum'
      fullPath: '/console/forum'
      preLoaderRoute: typeof AuthenticatedConsoleForumRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/financial': {
      id: '/_authenticated/console/financial'
      path: '/financial'
      fullPath: '/console/financial'
      preLoaderRoute: typeof AuthenticatedConsoleFinancialRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/courses': {
      id: '/_authenticated/console/courses'
      path: '/courses'
      fullPath: '/console/courses'
      preLoaderRoute: typeof AuthenticatedConsoleCoursesRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/coupons': {
      id: '/_authenticated/console/coupons'
      path: '/coupons'
      fullPath: '/console/coupons'
      preLoaderRoute: typeof AuthenticatedConsoleCouponsRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/certificates': {
      id: '/_authenticated/console/certificates'
      path: '/certificates'
      fullPath: '/console/certificates'
      preLoaderRoute: typeof AuthenticatedConsoleCertificatesRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/blog': {
      id: '/_authenticated/console/blog'
      path: '/blog'
      fullPath: '/console/blog'
      preLoaderRoute: typeof AuthenticatedConsoleBlogRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/api': {
      id: '/_authenticated/console/api'
      path: '/api'
      fullPath: '/console/api'
      preLoaderRoute: typeof AuthenticatedConsoleApiRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/account': {
      id: '/_authenticated/console/account'
      path: '/account'
      fullPath: '/console/account'
      preLoaderRoute: typeof AuthenticatedConsoleAccountRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
  }
}

interface AuthenticatedConsoleRouteChildren {
  AuthenticatedConsoleAccountRoute: typeof AuthenticatedConsoleAccountRoute
  AuthenticatedConsoleApiRoute: typeof AuthenticatedConsoleApiRoute
  AuthenticatedConsoleBlogRoute: typeof AuthenticatedConsoleBlogRoute
  AuthenticatedConsoleCertificatesRoute: typeof AuthenticatedConsoleCertificatesRoute
  AuthenticatedConsoleCouponsRoute: typeof AuthenticatedConsoleCouponsRoute
  AuthenticatedConsoleCoursesRoute: typeof AuthenticatedConsoleCoursesRoute
  AuthenticatedConsoleFinancialRoute: typeof AuthenticatedConsoleFinancialRoute
  AuthenticatedConsoleForumRoute: typeof AuthenticatedConsoleForumRoute
  AuthenticatedConsoleInstructorsRoute: typeof AuthenticatedConsoleInstructorsRoute
  AuthenticatedConsoleLearningRoute: typeof AuthenticatedConsoleLearningRoute
  AuthenticatedConsoleLessonsRoute: typeof AuthenticatedConsoleLessonsRoute
  AuthenticatedConsoleLogsRoute: typeof AuthenticatedConsoleLogsRoute
  AuthenticatedConsoleNotificationsRoute: typeof AuthenticatedConsoleNotificationsRoute
  AuthenticatedConsolePlansRoute: typeof AuthenticatedConsolePlansRoute
  AuthenticatedConsolePlaygroundRoute: typeof AuthenticatedConsolePlaygroundRoute
  AuthenticatedConsoleProfileRoute: typeof AuthenticatedConsoleProfileRoute
  AuthenticatedConsoleQuizzesRoute: typeof AuthenticatedConsoleQuizzesRoute
  AuthenticatedConsoleRealtimeRoute: typeof AuthenticatedConsoleRealtimeRoute
  AuthenticatedConsoleReposRoute: typeof AuthenticatedConsoleReposRoute
  AuthenticatedConsoleSecurityRoute: typeof AuthenticatedConsoleSecurityRoute
  AuthenticatedConsoleSettingsRoute: typeof AuthenticatedConsoleSettingsRoute
  AuthenticatedConsoleStudentsRoute: typeof AuthenticatedConsoleStudentsRoute
  AuthenticatedConsoleSupportRoute: typeof AuthenticatedConsoleSupportRoute
  AuthenticatedConsoleTrafficRoute: typeof AuthenticatedConsoleTrafficRoute
  AuthenticatedConsoleTransactionsRoute: typeof AuthenticatedConsoleTransactionsRoute
  AuthenticatedConsoleIndexRoute: typeof AuthenticatedConsoleIndexRoute
}

const AuthenticatedConsoleRouteChildren: AuthenticatedConsoleRouteChildren = {
  AuthenticatedConsoleAccountRoute: AuthenticatedConsoleAccountRoute,
  AuthenticatedConsoleApiRoute: AuthenticatedConsoleApiRoute,
  AuthenticatedConsoleBlogRoute: AuthenticatedConsoleBlogRoute,
  AuthenticatedConsoleCertificatesRoute: AuthenticatedConsoleCertificatesRoute,
  AuthenticatedConsoleCouponsRoute: AuthenticatedConsoleCouponsRoute,
  AuthenticatedConsoleCoursesRoute: AuthenticatedConsoleCoursesRoute,
  AuthenticatedConsoleFinancialRoute: AuthenticatedConsoleFinancialRoute,
  AuthenticatedConsoleForumRoute: AuthenticatedConsoleForumRoute,
  AuthenticatedConsoleInstructorsRoute: AuthenticatedConsoleInstructorsRoute,
  AuthenticatedConsoleLearningRoute: AuthenticatedConsoleLearningRoute,
  AuthenticatedConsoleLessonsRoute: AuthenticatedConsoleLessonsRoute,
  AuthenticatedConsoleLogsRoute: AuthenticatedConsoleLogsRoute,
  AuthenticatedConsoleNotificationsRoute:
    AuthenticatedConsoleNotificationsRoute,
  AuthenticatedConsolePlansRoute: AuthenticatedConsolePlansRoute,
  AuthenticatedConsolePlaygroundRoute: AuthenticatedConsolePlaygroundRoute,
  AuthenticatedConsoleProfileRoute: AuthenticatedConsoleProfileRoute,
  AuthenticatedConsoleQuizzesRoute: AuthenticatedConsoleQuizzesRoute,
  AuthenticatedConsoleRealtimeRoute: AuthenticatedConsoleRealtimeRoute,
  AuthenticatedConsoleReposRoute: AuthenticatedConsoleReposRoute,
  AuthenticatedConsoleSecurityRoute: AuthenticatedConsoleSecurityRoute,
  AuthenticatedConsoleSettingsRoute: AuthenticatedConsoleSettingsRoute,
  AuthenticatedConsoleStudentsRoute: AuthenticatedConsoleStudentsRoute,
  AuthenticatedConsoleSupportRoute: AuthenticatedConsoleSupportRoute,
  AuthenticatedConsoleTrafficRoute: AuthenticatedConsoleTrafficRoute,
  AuthenticatedConsoleTransactionsRoute: AuthenticatedConsoleTransactionsRoute,
  AuthenticatedConsoleIndexRoute: AuthenticatedConsoleIndexRoute,
}

const AuthenticatedConsoleRouteWithChildren =
  AuthenticatedConsoleRoute._addFileChildren(AuthenticatedConsoleRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAchievementsRoute: typeof AuthenticatedAchievementsRoute
  AuthenticatedCertificatesRoute: typeof AuthenticatedCertificatesRoute
  AuthenticatedConsoleRoute: typeof AuthenticatedConsoleRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedStatsRoute: typeof AuthenticatedStatsRoute
  AuthenticatedStudioRoute: typeof AuthenticatedStudioRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAchievementsRoute: AuthenticatedAchievementsRoute,
  AuthenticatedCertificatesRoute: AuthenticatedCertificatesRoute,
  AuthenticatedConsoleRoute: AuthenticatedConsoleRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedStatsRoute: AuthenticatedStatsRoute,
  AuthenticatedStudioRoute: AuthenticatedStudioRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  DownloadRoute: DownloadRoute,
  LeaderboardRoute: LeaderboardRoute,
  MissionsRoute: MissionsRoute,
  PlaygroundRoute: PlaygroundRoute,
  ProfileRoute: ProfileRoute,
  ProjectsRoute: ProjectsRoute,
  QuizRoute: QuizRoute,
  ToolsRoute: ToolsRoute,
  BlogSlugRoute: BlogSlugRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  LearnSlugRoute: LearnSlugRoute,
  LessonsIdRoute: LessonsIdRoute,
  PathsSlugRoute: PathsSlugRoute,
  VerifyCodeRoute: VerifyCodeRoute,
  BlogIndexRoute: BlogIndexRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  LearnIndexRoute: LearnIndexRoute,
  LessonsIndexRoute: LessonsIndexRoute,
  PathsIndexRoute: PathsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
