/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PathsIndexRouteImport } from './routes/paths/index'
import { Route as LessonsIndexRouteImport } from './routes/lessons/index'
import { Route as PathsSlugRouteImport } from './routes/paths/$slug'
import { Route as LessonsIdRouteImport } from './routes/lessons/$id'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PathsIndexRoute = PathsIndexRouteImport.update({
  id: '/paths/',
  path: '/paths/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsIndexRoute = LessonsIndexRouteImport.update({
  id: '/lessons/',
  path: '/lessons/',
  getParentRoute: () => rootRouteImport,
} as any)
const PathsSlugRoute = PathsSlugRouteImport.update({
  id: '/paths/$slug',
  path: '/paths/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsIdRoute = LessonsIdRouteImport.update({
  id: '/lessons/$id',
  path: '/lessons/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/leaderboard': typeof LeaderboardRoute
  '/missions': typeof MissionsRoute
  '/playground': typeof PlaygroundRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/quiz': typeof QuizRoute
  '/tools': typeof ToolsRoute
  '/lessons/$id': typeof LessonsIdRoute
  '/paths/$slug': typeof PathsSlugRoute
  '/lessons/': typeof LessonsIndexRoute
  '/paths/': typeof PathsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/leaderboard': typeof LeaderboardRoute
  '/missions': typeof MissionsRoute
  '/playground': typeof PlaygroundRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/quiz': typeof QuizRoute
  '/tools': typeof ToolsRoute
  '/lessons/$id': typeof LessonsIdRoute
  '/paths/$slug': typeof PathsSlugRoute
  '/lessons': typeof LessonsIndexRoute
  '/paths': typeof PathsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/leaderboard': typeof LeaderboardRoute
  '/missions': typeof MissionsRoute
  '/playground': typeof PlaygroundRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/quiz': typeof QuizRoute
  '/tools': typeof ToolsRoute
  '/lessons/$id': typeof LessonsIdRoute
  '/paths/$slug': typeof PathsSlugRoute
  '/lessons/': typeof LessonsIndexRoute
  '/paths/': typeof PathsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/leaderboard'
    | '/missions'
    | '/playground'
    | '/profile'
    | '/projects'
    | '/quiz'
    | '/tools'
    | '/lessons/$id'
    | '/paths/$slug'
    | '/lessons/'
    | '/paths/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/leaderboard'
    | '/missions'
    | '/playground'
    | '/profile'
    | '/projects'
    | '/quiz'
    | '/tools'
    | '/lessons/$id'
    | '/paths/$slug'
    | '/lessons'
    | '/paths'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/leaderboard'
    | '/missions'
    | '/playground'
    | '/profile'
    | '/projects'
    | '/quiz'
    | '/tools'
    | '/lessons/$id'
    | '/paths/$slug'
    | '/lessons/'
    | '/paths/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LeaderboardRoute: typeof LeaderboardRoute
  MissionsRoute: typeof MissionsRoute
  PlaygroundRoute: typeof PlaygroundRoute
  ProfileRoute: typeof ProfileRoute
  ProjectsRoute: typeof ProjectsRoute
  QuizRoute: typeof QuizRoute
  ToolsRoute: typeof ToolsRoute
  LessonsIdRoute: typeof LessonsIdRoute
  PathsSlugRoute: typeof PathsSlugRoute
  LessonsIndexRoute: typeof LessonsIndexRoute
  PathsIndexRoute: typeof PathsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paths/': {
      id: '/paths/'
      path: '/paths'
      fullPath: '/paths/'
      preLoaderRoute: typeof PathsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/': {
      id: '/lessons/'
      path: '/lessons'
      fullPath: '/lessons/'
      preLoaderRoute: typeof LessonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paths/$slug': {
      id: '/paths/$slug'
      path: '/paths/$slug'
      fullPath: '/paths/$slug'
      preLoaderRoute: typeof PathsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/$id': {
      id: '/lessons/$id'
      path: '/lessons/$id'
      fullPath: '/lessons/$id'
      preLoaderRoute: typeof LessonsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LeaderboardRoute: LeaderboardRoute,
  MissionsRoute: MissionsRoute,
  PlaygroundRoute: PlaygroundRoute,
  ProfileRoute: ProfileRoute,
  ProjectsRoute: ProjectsRoute,
  QuizRoute: QuizRoute,
  ToolsRoute: ToolsRoute,
  LessonsIdRoute: LessonsIdRoute,
  PathsSlugRoute: PathsSlugRoute,
  LessonsIndexRoute: LessonsIndexRoute,
  PathsIndexRoute: PathsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
